name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.9'

      - name: Exécuter le script Python
        run: python.py